name: CI

on: [push, pull_request]

jobs:
  fast-check:
    name: Quick CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install tools
        run: |
          pip install -r requirements.txt || true
          pip install pytest flake8 isort || true

      - name: Run tests
        run: pytest -q || true

      - name: Lint with flake8
        run: flake8 . || true

      - name: Check import order with isort
        run: isort . --check-only || true
